# This is a basic workflow to help you get started with Actions

<h1 id="title">Owning pets Survey Form </h1>
<p id="description">We would love to know if you have any pets at the moment</p>

<form id ="survey-form"> 


<label id="name-label">Enter  your full name:</label>

  <input id="name" placeholder="John Smith" type ="text" required >

<label id="email-label">Enter  your e-mail:</label>

<input id="email" placeholder="firstname.lastname@gmail.com" type ="email" required >

<label id="number-label">What is your age?</label>

<input number id="number" placeholder ="18" type ="number" min ="1" max="120">



<label>How many pets do you have at the moment?
  <select id="dropdown" name="dropdown">
    <option value="1">I don't have any pets</option>
    <option value="2">I have one pet</option>
     <option value ="3">I have two or more pets</option>
    <select>

<fieldset id="Cat lovers">I love cats: Yes/No
        <input type="radio" value="cat" name="Cat lovers">
        <input type="radio" value="cat 2" name="Cat lovers">
    </fieldset>

    <fieldset id="Dog lovers">I love dogs: Yes/No
        <input type="radio" value="dog" name="Dog lovers">
        <input type="radio" value="dog 2" name="Dog lovers">
     </fieldset>   


 <label><input type="checkbox" required value="terms"/> I accept the terms and conditions</label>

 <label><input type="checkbox" required value="newsletter"/> I would like to receive weekly newsletters </label>


<input id="submit" type="submit" value="Submit" />
<textarea>Tell me something you love about pets
